package com.fh.entity.qizhe;

import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;

public class ProjectAuditHelperJXD {

    public static Map<String, String> PROJECT_INFO = new LinkedHashMap<>();

    public static Map<String, String> UPPER_CASE_INFO = new HashMap<>();

    public static Map<String, String> PROJECT_HELP = new HashMap<>();

    static {
        PROJECT_INFO.put("1", "苏宁店招需保持显眼干净；不得破损、脏旧、褪色；在同一经营区域内不得出现其他同类经营体门头（如某某家电经营部等商户自有门头）");
        PROJECT_INFO.put("2", "外墙外立面、玻璃幕墙干净，外部橱窗玻璃干净整洁、明亮通透");
        PROJECT_INFO.put("3", "店外布展氛围不得弱于周边商户，如横幅、游字屏、帐篷、道旗、X展架、水牌等需选择2种以上布展，且不得有过期物料\n" + "（部分区域户外管控，不允许进行布展，可对标周边商户）");
        PROJECT_INFO.put("4", "店内经营区域内环境整洁，通道畅通，无杂乱堆放");
        PROJECT_INFO.put("5", "店内陈列非精选店经营的产品（家电、通讯类）");
        PROJECT_INFO.put("6", "样机/展台需干净整洁，不得有大量灰尘、污渍；");
        PROJECT_INFO.put("7", "样机/展台上不得随意放置私人物品（如衣服、包等），可容性样机（冰箱、洗衣机、电饭煲、微波炉等小家电）放置杂物，如水瓶、剩饭菜等");
        PROJECT_INFO.put("8", "样机需整齐摆放，不得出现明显缺样（每个品类有两个及以上缺样，可判定为明显缺样；有临时换样情况不扣分）");
        PROJECT_INFO.put("9", "门店彩电是否有开启，开启台数原则上不得低于门店一半的出样台数");
        PROJECT_INFO.put("10", "店内整体布展氛围较好，能直观感受到促销氛围；");
        PROJECT_INFO.put("11", "店内不允许存在过期物料，如618大促店内出现五一促销的物料，（以大促后十天为调整期）");
        PROJECT_INFO.put("12", "每台样机必须都要粘贴价签（新上市贴展示品的除外），不允许用手写价签或使用其他物料代替价签；");
        PROJECT_INFO.put("13", "门店品牌展厅、展台出样品牌符合");
        PROJECT_INFO.put("14", "店员未穿着带有精选店字样或苏宁LOGO工装");
        PROJECT_INFO.put("15", "1-现场不得坐岗、趴柜、靠柜、倚坐柜台以及聚岗现象；\n" + "2-人员现场玩游戏以及其他与工作无关事情（一般以手机横版状态基本判定为违规）");
        PROJECT_INFO.put("16", "顾客临近展厅展柜查看商品后，现场销售人员需及时接待；");
        PROJECT_INFO.put("17", "销售人员需熟悉产品特点，能较为流畅的介绍（建议询问惠而浦品牌：这个空调什么牌子的？若能详细讲解匹数、性能、定/变频、是否静音等特点则为流畅）");
        PROJECT_INFO.put("18", "顾客咨询商品但不购买的情况下，销售人员需主动留取顾客信息（加微信），以便促进后期发送促销信息、跟进销售达成；");
        PROJECT_INFO.put("19", "顾客咨询商品但不购买的情况下，销售人员不得出现对顾客不屑、不耐烦甚至谩骂的恶劣态度");
        PROJECT_INFO.put("20", "在暗访人员（或现场顾客）有要求的情况下，拒绝开具发票。");
        PROJECT_INFO.put("21", "店内未使用零售云货架APP进行展示（含TV端、Pad端） ");
        PROJECT_INFO.put("22", "店员不会操作或无法熟练使用零售云货架APP");
        PROJECT_INFO.put("23", "门店存在直接销售非苏宁商品的行为");
        PROJECT_INFO.put("24", "门店存在介绍、诱导顾客至非苏宁销售渠道外的第三方购买商品，向第三方泄露顾客安装等服务信息，意图促成第三方与顾客交易的行为");
        PROJECT_INFO.put("25", "检查人员认为门店所在商圈如何？");
        PROJECT_INFO.put("26", "随机抽查三个顾客，是否知晓苏宁易购品牌？");
        PROJECT_INFO.put("27", "随机抽查三个顾客，是否看到过门店的宣传？（海报、横幅等）");
        PROJECT_INFO.put("28", "检查人员针对本次检查的门店有何优化建议");


        for (String key : PROJECT_INFO.keySet()) {
            UPPER_CASE_INFO.put(key, key.toUpperCase());
        }


       PROJECT_HELP.put("a01", "　　　　　　　　　　　　　　");
   /*      PROJECT_HELP.put("a02", "　");
        PROJECT_HELP.put("a03", "　一定时期后应全部清除加油站");
        PROJECT_HELP.put("a04", "　暂不考核");
        PROJECT_HELP.put("a05", "可用A4纸黑白打印装订成册　");
        PROJECT_HELP.put("a06", "先期考核办公室、加油现场（含站房四周）、配发电间、厨房餐厅、员工宿舍、活动室，2018年7月起全面考核　");
        PROJECT_HELP.put("a07", "先期考核办公室、加油现场（含站房四周）、配发电间、厨房餐厅、员工宿舍、活动室，2018年7月起全面考核　");
        PROJECT_HELP.put("a08", "　");
        PROJECT_HELP.put("a09", "　暂不考核，规范后考核");
        PROJECT_HELP.put("a10", "其它项有考核的除外　");
        PROJECT_HELP.put("a11", "重点关注顾客可视的加油现场、加油设备、主立牌灯箱、罩棚、立柱、墙面、绿化等，其它项有考核的除外　");
        PROJECT_HELP.put("a12", "　暂不考核，2018年7月起全面考核");
        PROJECT_HELP.put("a13", "　暂不考核，2018年7月起全面考核");
        PROJECT_HELP.put("a14", "　");
        PROJECT_HELP.put("a15", "　");
        PROJECT_HELP.put("a16", "　办公室可放置在个人物品柜里，加油现场可根据需要设置物品整理箱");
        PROJECT_HELP.put("a17", "　");
        PROJECT_HELP.put("a18", "　备用帐表册可叠放，不用放于档案盒");
        PROJECT_HELP.put("a19", "　");
        PROJECT_HELP.put("a20", "一组电源开关一个　");
        PROJECT_HELP.put("a21", "　");
        PROJECT_HELP.put("a22", "　便利店内可安装在柜门内侧");
        PROJECT_HELP.put("a23", "　");
        PROJECT_HELP.put("a24", "　");
        PROJECT_HELP.put("a25", "卫生间洗手盆的水龙头已粘贴“请节约用水”提示的除外　");
        PROJECT_HELP.put("a26", "左右开启的窗帘不设开启线，但开启状态应统一　");
        PROJECT_HELP.put("a27", "　");
        PROJECT_HELP.put("a28", "粘贴在高处，粘贴方式需优化　");
        PROJECT_HELP.put("a29", "　其它项有考核的除外");
        PROJECT_HELP.put("a30", "　");
        PROJECT_HELP.put("a31", "初期室内未作隐蔽处理，但只有一个线槽的考核　");
        PROJECT_HELP.put("a32", "暂不考核，适用于2017年及以后新建投运或实施站房技改的加油站　");
        PROJECT_HELP.put("b01", "参照细节管理手册，侧重加油岛和标准物件，垃圾桶不需要每岛一个　");
        PROJECT_HELP.put("b02", "暂不考核，2018年5月20日起全面考核　");
        PROJECT_HELP.put("b03", "　暂不考核，2018年5月20日起全面考核");
        PROJECT_HELP.put("b04", "　暂不考核，2018年5月20日起全面考核");
        PROJECT_HELP.put("b05", "直径约30cm为宜，分公司内统一型号，不具备条件的可不配置　");
        PROJECT_HELP.put("b06", "先期考核办公室、加油现场（含站房四周）、配发电间、厨房餐厅、员工宿舍、活动室，2018年7月起全面考核　");
        PROJECT_HELP.put("b07", "绿植除外　");
        PROJECT_HELP.put("b08", "　");
        PROJECT_HELP.put("b09", "　便利店前、加油现场");
        PROJECT_HELP.put("b10", "暂不考核　");
        PROJECT_HELP.put("b11", "加油枪直接向摩托车加油的除外　");
        PROJECT_HELP.put("b12", "　加油枪直接向摩托车加油的除外");
        PROJECT_HELP.put("b13", "　");
        PROJECT_HELP.put("b14", "　");
        PROJECT_HELP.put("b15", "　");
        PROJECT_HELP.put("b16", "　暂不考核");
        PROJECT_HELP.put("B17", "结合实际情况评判是否扣分　");
        PROJECT_HELP.put("b18", "　厕所设置在便利店内的，厕所内可适量设置拖把");
        PROJECT_HELP.put("b19", "　");
        PROJECT_HELP.put("b20", "　");
        PROJECT_HELP.put("b21", "　");
        PROJECT_HELP.put("b22", "　暂不考核，适用于2017年及以后新建投运或实施管线改造的加油站");
        PROJECT_HELP.put("b23", "　暂不考核，适用于2017年及以后新建投运或实施管线改造的加油站");
        PROJECT_HELP.put("b24", "尽量掩蔽，不宜多设　");
        PROJECT_HELP.put("c01", "办公桌一般不超过3张；一楼设置办公室的，二楼一般不再设置　");
        PROJECT_HELP.put("c02", "　");
        PROJECT_HELP.put("c03", "　一定时期后应全部清除加油站");
        PROJECT_HELP.put("c04", "");
        PROJECT_HELP.put("c05", "从上到下一般为“办公文具”“常用文件”“个人物品”，按需设置　");
        PROJECT_HELP.put("c06", "　");
        PROJECT_HELP.put("c07", "");
        PROJECT_HELP.put("c08", "　上层“文件资料”，下层“办公用品”");
        PROJECT_HELP.put("c09", "有三层的，最下面一层可设置资料篮，整齐放置待装订资料");
        PROJECT_HELP.put("c10", "暂不考核，有特殊要求的除外　");
        PROJECT_HELP.put("c11", "其它地方摆放办公用品的暂不考核，2019年1月1日起执行考核　");
        PROJECT_HELP.put("c12", "　多余空间可放置备用账表册");
        PROJECT_HELP.put("c13", "　与标签不符暂不考核，需完善分类优化");
        PROJECT_HELP.put("c14", "其它文件柜不设置二级清单　");
        PROJECT_HELP.put("c15", "　");
        PROJECT_HELP.put("c16", "　文件夹可用A4纸长边制作");
        PROJECT_HELP.put("c17", "备用清洁用品、常用工具不得放置在文件柜内（防爆电筒除外），不首选设置在办公室内（无条件的除外）　");
        PROJECT_HELP.put("c18", "　不设置二级清单");
        PROJECT_HELP.put("c19", "　");
        PROJECT_HELP.put("c20", "二楼办公室不粘贴，便利店库房不粘贴　");
        PROJECT_HELP.put("c21", "桌面物品、主机箱　");
        PROJECT_HELP.put("c22", "　");
        PROJECT_HELP.put("c23", "方便实用就可以　");
        PROJECT_HELP.put("c24", "暂不考核　");
        PROJECT_HELP.put("c25", "　");
        PROJECT_HELP.put("c26", "　");
        PROJECT_HELP.put("c27", "　键盘、鼠标、显示器共用");
        PROJECT_HELP.put("c28", "　");
        PROJECT_HELP.put("c29", "　");
        PROJECT_HELP.put("c30", "　");
        PROJECT_HELP.put("c31", "");
        PROJECT_HELP.put("d01", "提出优化建议　");
        PROJECT_HELP.put("d02", "　台面下不能放置收银钱箱的可用抽屉，尽量不取消");
        PROJECT_HELP.put("d03", "　");
        PROJECT_HELP.put("d04", "");
        PROJECT_HELP.put("d05", "　");
        PROJECT_HELP.put("d06", "　");
        PROJECT_HELP.put("d07", "");
        PROJECT_HELP.put("d08", "　提出优化建议（保险柜、非油商品、收银钱箱不粘贴？）");
        PROJECT_HELP.put("d09", "");
        PROJECT_HELP.put("d10", "需细化描述　");
        PROJECT_HELP.put("d11", "文件夹标签可用A4纸长边制作　");
        PROJECT_HELP.put("d12", "　");
        PROJECT_HELP.put("d13", "　有必要设置的设备除外");
        PROJECT_HELP.put("d14", "　");
        PROJECT_HELP.put("d15", "　");
        PROJECT_HELP.put("d16", "　");
        PROJECT_HELP.put("d17", "　");
        PROJECT_HELP.put("d18", "　");
        PROJECT_HELP.put("d19", "　");
        PROJECT_HELP.put("d20", "　");
        PROJECT_HELP.put("e01", "广告灯箱光源须全时段开启；8点至17点59分，光线充足的站，吊顶灯须开启50%以上；18点至第二天7点59分，吊顶灯须全部开启；有报修记录的除外　");
        PROJECT_HELP.put("e02", "在顾客能够触及到地方，所放置的商品均应用于销售，为此，必须要明码标价（有价签或POP/爆炸卡均可），且价签须靠左陈列。　");
        PROJECT_HELP.put("e03", "　商品的正面应面向顾客。");
        PROJECT_HELP.put("e04", "为保证商品的丰满和量感陈列，以及易于顾客取拿的原则，加油站应主动调整货架层板与商品的间距，保持不少于二指的高度和不多于三到四指的高度。");
        PROJECT_HELP.put("e05", "");
        PROJECT_HELP.put("e06", "普通货架每90公分货架长度，缺货超过30公分，视为严重缺货。回型货架单个层板缺货超过一半，视为严重缺货。　");
        PROJECT_HELP.put("e07", "");
        PROJECT_HELP.put("e08", "室内堆头原则上总高度不超过0.8米，如有特殊陈列须向公司报备，有报备手续的除外。靠壁堆头首层须割箱陈列。");
        PROJECT_HELP.put("e09", "原则不得遮挡橱窗玻璃，地堆高度0.8米为宜，高于1米的视为过高。");
        PROJECT_HELP.put("e10", "针对岛上有堆头加油站进行考核　");
        PROJECT_HELP.put("e11", "针对有快餐区的加油站　");
        PROJECT_HELP.put("e12", "　标准店及高级店纳入考核，顾客目视可及的地方均纳入考核范围，可放置促销赠品");
        PROJECT_HELP.put("e13", "　针对有购物篮、购物车的加油站");
        PROJECT_HELP.put("e14", "　");
        PROJECT_HELP.put("e15", "　");
        PROJECT_HELP.put("e16", "　");
        PROJECT_HELP.put("e17", "磁性拨码器是用来方便库房计算进出货数量品种、盘库用的　");
        PROJECT_HELP.put("e18", "　");
        PROJECT_HELP.put("e19", "针对开展快餐业务的加油站，应在熟食类商品存储区域张贴管控表　");
        PROJECT_HELP.put("e20", "非入库赠品指非卖品赠品。　");
        PROJECT_HELP.put("e21", "　");
        PROJECT_HELP.put("e22", "　");
        PROJECT_HELP.put("e23", "　");
        PROJECT_HELP.put("e24", "　");
        PROJECT_HELP.put("e25", "　");
        PROJECT_HELP.put("e26", "　");
        PROJECT_HELP.put("e27", "无便利店的放置在办公室适当位置");
        PROJECT_HELP.put("f01", "　");
        PROJECT_HELP.put("f02", "　");
        PROJECT_HELP.put("f03", "　不要求粘贴定位标识标线");
        PROJECT_HELP.put("f04", "");
        PROJECT_HELP.put("f05", "");
        PROJECT_HELP.put("f06", "　");
        PROJECT_HELP.put("f07", "");
        PROJECT_HELP.put("f08", "");
        PROJECT_HELP.put("f09", "");
        PROJECT_HELP.put("f10", "　");
        PROJECT_HELP.put("f11", "　");
        PROJECT_HELP.put("f12", "");
        PROJECT_HELP.put("f13", "　");
        PROJECT_HELP.put("f14", "　");
        PROJECT_HELP.put("f15", "　暂不考核");
        PROJECT_HELP.put("f16", "　参照细节管理手册");
        PROJECT_HELP.put("f17", "随机抽查两名现场当班员工的员工柜　");
        PROJECT_HELP.put("f18", "　");
        PROJECT_HELP.put("f19", "　");
        PROJECT_HELP.put("f20", "　");
        PROJECT_HELP.put("f21", "　");
        PROJECT_HELP.put("f22", "　");
        PROJECT_HELP.put("f23", "　主要针对未明确考核标准的区域");
        PROJECT_HELP.put("g01", "　90度指示牌仅用于厕所不醒目的站");
        PROJECT_HELP.put("g02", "　");
        PROJECT_HELP.put("g03", "　五种提示牌");
        PROJECT_HELP.put("g04", "");
        PROJECT_HELP.put("g05", "");
        PROJECT_HELP.put("g06", "暂不考核　");
        PROJECT_HELP.put("g07", "直径约30cm为宜，分公司内统一型号");
        PROJECT_HELP.put("g08", "");
        PROJECT_HELP.put("g09", "");
        PROJECT_HELP.put("g10", "　");
        PROJECT_HELP.put("g11", "　");
        PROJECT_HELP.put("g12", "");
        PROJECT_HELP.put("g13", "　");
        PROJECT_HELP.put("g14", "　");
        PROJECT_HELP.put("g15", "　");
        PROJECT_HELP.put("g16", "　重点检查可视部分");
        PROJECT_HELP.put("g17", "　");
        PROJECT_HELP.put("g18", "　");
        PROJECT_HELP.put("g19", "　");
        PROJECT_HELP.put("g20", "　");*/

    }
}
