package com.fh.entity.qizhe;

import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;

public class ProjectAuditHelper {

    public static Map<String, String> PROJECT_INFO = new LinkedHashMap<>();

    public static Map<String, String> UPPER_CASE_INFO = new HashMap<>();

    public static Map<String, String> PROJECT_HELP = new HashMap<>();

    static {
        PROJECT_INFO.put("C1.1", "店外招牌、玻璃清洁无污渍，无旧海报未刮干净留下的胶渍【顾客进店时看到的玻璃门周边】");
        PROJECT_INFO.put("C1.2", "门店外三米内地面整洁干净，无纸屑、烟头、杂物，屋檐无蜘蛛网");
        PROJECT_INFO.put("C1.3", "店内外地垫整洁干净，无纸屑、烟头、杂物");
        PROJECT_INFO.put("C1.4", "店内垃圾桶整体干净，无垃圾袋外露，推板完好，桶内垃圾不超过整体2/3");
        PROJECT_INFO.put("C2.1", "店内天花板无蜘蛛网，地板无垃圾，无污渍，无铺纸皮【下雨天不考评地板污渍】；\n" + "门店有将 '小心地滑' 指示牌立出【下雨天考评】");
        PROJECT_INFO.put("C2.2", "购物篮清洁无污渍、油渍，且数量不低于3个");
        PROJECT_INFO.put("C3.1", "顾客结账时观察收银前后柜台，台面干净整洁，无污渍，无杂物，无文件，无私人物品【任一不合格即扣分】");
        PROJECT_INFO.put("C4.1", "货架清洁无灰尘、虫尸【货架及商品同时考评，任一不合格即扣分】");
        PROJECT_INFO.put("C5.1", "休闲区桌面干净，无污渍，无垃圾，桌椅摆放整齐【如果速食台有顾客坐着，就不考核桌椅摆放整齐】  休闲区有3人以上使用，则不考评整齐及清洁度");
        PROJECT_INFO.put("Q1.1", "店内所有货架的价签破损或缺失数总计≤5个则得分");
        PROJECT_INFO.put("Q2.1", "店外海报张贴在腰线以下，且门店所有海报张贴工整，橱窗海报没有过期内容");
        PROJECT_INFO.put("Q2.2", "店内TV设备正常播放，无过期促销活动或宣传视频等内容，没有播放电视剧或者电影");
        PROJECT_INFO.put("Q2.3", "进店时，门铃正常播放，并且音量适中【地铁店不考核，直接得分】");
        PROJECT_INFO.put("Q2.4", "店内音乐播放正常，音量适中，营造出购物环境");
        PROJECT_INFO.put("Q3.1", "店内陈列水果、蔬菜无坏品【无水果蔬菜则直接得分】\n" + "若发现有明显坏品、果蔬腐烂，则该门店当月点检成绩计0。");
        PROJECT_INFO.put("Q4.1", "卧式冷冻冰柜商品整洁，无破损，无挤压变形，无空框，价签无破损，张贴整齐");
        PROJECT_INFO.put("Q4.2", "冰柜内冰品陈列不超过红色警戒线，柜壁冰霜厚度不超过1cm则得分（须附照片），冰柜推拉门保持关闭，有一项没有做到即扣分。");
        PROJECT_INFO.put("Q5.1", "风幕柜货架未前进陈列数≤3个则得分");
        PROJECT_INFO.put("Q5.2", "检查风幕柜饭团陈列量，饭团品项数不低于3个，饭团总数量不低于9个则得分");
        PROJECT_INFO.put("Q5.3", "抽查3瓶酸奶或3份盒饭保质期，商品均在保质期内则得分\n" + "若发现有任意一瓶酸奶或一份盒饭过期，则该门店当月点检成绩计0。");
        PROJECT_INFO.put("Q6.1", "饮料冷藏柜货架未前进陈列数≤3个则得分 ");
        PROJECT_INFO.put("Q6.2", "饮料冷藏柜货架欠品数≤2个则得分");
        PROJECT_INFO.put("Q7.1", "常温商品单层货架上的未前进陈列数＜2个则得分");
        PROJECT_INFO.put("Q7.2", "常温商品所有货架欠品数＜2个则得分");
        PROJECT_INFO.put("Q7.3", "检查面包货架（如未发现面包货架即扣分），面包品项数不低于6个，面包总数量不低于12个");
        PROJECT_INFO.put("Q7.4", "抽查3个面包保质期，商品均在保质期内则得分\n" + "若发现有面包过期，则该门店当月点检成绩计0。");
        PROJECT_INFO.put("Q8.1", "关东煮无发黑品项，品项数不低于5个，总数不低于15个（备注：收银台无此设备即得分）");
        PROJECT_INFO.put("Q8.2", "烤肠机陈列数量不低于5个，无发黑品质、无表皮爆裂品相（备注：收银台无此设备即得分）");
        PROJECT_INFO.put("Q8.3", "蒸包机陈列数量不低于12个（备注：收银台无此设备即得分）");
        PROJECT_INFO.put("S1", "客人进店时，员工与顾客有眼神接触并使用“欢迎光临”“您好”等招呼问候用语表示欢迎，声音宏亮，口齿清晰。\n"
            + "在神秘顾客本人经历过程中，员工对所有顾客进店均有问候语则该题给分");
        PROJECT_INFO.put("S2", "顾客进店时促销：客人进店欢迎光临后有当月促销用语或活动宣传，声音宏亮，口齿清晰，话语完整。 【购物过程中，有员工主动上前为顾客介绍当月活动或商品也不扣分】");
        PROJECT_INFO.put("S3", "顾客结账前：店员向顾客推荐下载小店APP，“在家下单，购物满18元免费配送。”推荐小店APP小店下载即可得分。");
        PROJECT_INFO.put("S4", "顾客结账时：主动询问顾客是否有别的需求，主动询问“您好，还需要点什么吗？”或者主动面销相关活动或商品【声音宏亮，口齿清晰，话语完整】对顾客的购买，进行关联性活动或商品的面销都可得分");
        PROJECT_INFO.put("S5", "顾客结账时：购物2件及以上商品时，是否主动为顾客提供购物袋或询问顾客“请问需要购物袋吗？”");
        PROJECT_INFO.put("S6", "顾客结账时：主动帮顾客装袋并双手将装好商品的购物袋递给顾客。\n" + "【如果顾客有购买盒饭等需要餐具，须主动附上餐具，购买冷藏酸奶配上吸管等】。");
        PROJECT_INFO.put("S7", "顾客结账时，收银时是否向顾客报出应收的总金额，以神秘顾客实际体验为评分标准");
        PROJECT_INFO.put("S8", "顾客结账时，主动询问顾客的支付方式，“您好，请问有苏宁金融吗？“（苏宁金融新用户，首单满15立减14.99元，此活动以实际情况为准）");
        PROJECT_INFO.put("S9", "顾客付款后，主动向顾客呈递购物小票及找零【含刷卡】，没有双手呈递或者没有递交收银小票都不得分");
        PROJECT_INFO.put("S10", "顾客离开门店时，员工有向顾客表示谢意：“谢谢光临”，“欢迎下次再来or欢迎常来”等告别用语，在神秘顾客本人的经历过程中，员工对所有顾客离店均有告别用语则该题给分");
        PROJECT_INFO.put("S11", "购物体验：在整个结账过程中，员工面带微笑，目光友善，服务有亲和力，自然流畅。");
        PROJECT_INFO.put("S12.1", "工服要求：门店所有员工必须着‘苏宁小店’工服上班，且工服干净。裤子：只能穿蓝色、深色牛仔长裤，或蓝色、深色无其它装饰休闲长裤，长裤长度须覆盖脚踝。鞋子：穿运动鞋，不得穿拖鞋式跑鞋、皮鞋、凉鞋、拖鞋、高跟鞋。\n"
            + "任意一条不合格则扣分。");
        PROJECT_INFO.put("S12.2", "员工不得留长指甲，不得染鲜艳、夸张发色，女生刘海不得遮住眼睛，不得披头散发，头发及肩须扎起，女生不得化浓妆；男生不得留胡须，前面头发不得超过眉毛，两侧头发必须露出整个耳朵，鬓角不得超过耳垂，后面头发高出衣领。\n"
            + "上班期间不得佩戴装饰物，不戴耳环、耳钉、项链、戒指、手表或者手镯等装饰物。\n" + "任意一条不合格则扣分。");
        PROJECT_INFO.put("S13.1", "员工在店内不得穿制服在卖场内发消息、接手机、玩手机、看视频【工作除外】\n"
            + "不得将双手插在裤子口袋内、不得倚靠柜台、不得双手交叉放于胸前、不得抖脚       \n" + "不得穿制服在卖场吃东西 、不得在卖场内嬉戏玩耍、不得吸烟喝酒、不聚众聊天 、不得在收银台里喝水    \n"
            + "不得有不礼貌的目光注视顾客，不得与顾客争论，不得以不友好的态度接待顾客     \n" + "任意一条不合格则扣分。  ");
        PROJECT_INFO.put("S13.2", "门店内货物或运货推车等物品不得堵塞购物通道，商品不得直接落地，不得影响顾客购物和店面整体形象。");
        PROJECT_INFO.put("S14", "员工在向顾客销售热食时，戴好口罩、手套，佩戴时必须无破损，盖住鼻子，不得挂在耳朵上或下鄂上");


        for (String key : PROJECT_INFO.keySet()) {
            UPPER_CASE_INFO.put(key, key.toUpperCase());
        }


    /*    PROJECT_HELP.put("a01", "　");
        PROJECT_HELP.put("a02", "　");
        PROJECT_HELP.put("a03", "　一定时期后应全部清除加油站");
        PROJECT_HELP.put("a04", "　暂不考核");
        PROJECT_HELP.put("a05", "可用A4纸黑白打印装订成册　");
        PROJECT_HELP.put("a06", "先期考核办公室、加油现场（含站房四周）、配发电间、厨房餐厅、员工宿舍、活动室，2018年7月起全面考核　");
        PROJECT_HELP.put("a07", "先期考核办公室、加油现场（含站房四周）、配发电间、厨房餐厅、员工宿舍、活动室，2018年7月起全面考核　");
        PROJECT_HELP.put("a08", "　");
        PROJECT_HELP.put("a09", "　暂不考核，规范后考核");
        PROJECT_HELP.put("a10", "其它项有考核的除外　");
        PROJECT_HELP.put("a11", "重点关注顾客可视的加油现场、加油设备、主立牌灯箱、罩棚、立柱、墙面、绿化等，其它项有考核的除外　");
        PROJECT_HELP.put("a12", "　暂不考核，2018年7月起全面考核");
        PROJECT_HELP.put("a13", "　暂不考核，2018年7月起全面考核");
        PROJECT_HELP.put("a14", "　");
        PROJECT_HELP.put("a15", "　");
        PROJECT_HELP.put("a16", "　办公室可放置在个人物品柜里，加油现场可根据需要设置物品整理箱");
        PROJECT_HELP.put("a17", "　");
        PROJECT_HELP.put("a18", "　备用帐表册可叠放，不用放于档案盒");
        PROJECT_HELP.put("a19", "　");
        PROJECT_HELP.put("a20", "一组电源开关一个　");
        PROJECT_HELP.put("a21", "　");
        PROJECT_HELP.put("a22", "　便利店内可安装在柜门内侧");
        PROJECT_HELP.put("a23", "　");
        PROJECT_HELP.put("a24", "　");
        PROJECT_HELP.put("a25", "卫生间洗手盆的水龙头已粘贴“请节约用水”提示的除外　");
        PROJECT_HELP.put("a26", "左右开启的窗帘不设开启线，但开启状态应统一　");
        PROJECT_HELP.put("a27", "　");
        PROJECT_HELP.put("a28", "粘贴在高处，粘贴方式需优化　");
        PROJECT_HELP.put("a29", "　其它项有考核的除外");
        PROJECT_HELP.put("a30", "　");
        PROJECT_HELP.put("a31", "初期室内未作隐蔽处理，但只有一个线槽的考核　");
        PROJECT_HELP.put("a32", "暂不考核，适用于2017年及以后新建投运或实施站房技改的加油站　");
        PROJECT_HELP.put("b01", "参照细节管理手册，侧重加油岛和标准物件，垃圾桶不需要每岛一个　");
        PROJECT_HELP.put("b02", "暂不考核，2018年5月20日起全面考核　");
        PROJECT_HELP.put("b03", "　暂不考核，2018年5月20日起全面考核");
        PROJECT_HELP.put("b04", "　暂不考核，2018年5月20日起全面考核");
        PROJECT_HELP.put("b05", "直径约30cm为宜，分公司内统一型号，不具备条件的可不配置　");
        PROJECT_HELP.put("b06", "先期考核办公室、加油现场（含站房四周）、配发电间、厨房餐厅、员工宿舍、活动室，2018年7月起全面考核　");
        PROJECT_HELP.put("b07", "绿植除外　");
        PROJECT_HELP.put("b08", "　");
        PROJECT_HELP.put("b09", "　便利店前、加油现场");
        PROJECT_HELP.put("b10", "暂不考核　");
        PROJECT_HELP.put("b11", "加油枪直接向摩托车加油的除外　");
        PROJECT_HELP.put("b12", "　加油枪直接向摩托车加油的除外");
        PROJECT_HELP.put("b13", "　");
        PROJECT_HELP.put("b14", "　");
        PROJECT_HELP.put("b15", "　");
        PROJECT_HELP.put("b16", "　暂不考核");
        PROJECT_HELP.put("B17", "结合实际情况评判是否扣分　");
        PROJECT_HELP.put("b18", "　厕所设置在便利店内的，厕所内可适量设置拖把");
        PROJECT_HELP.put("b19", "　");
        PROJECT_HELP.put("b20", "　");
        PROJECT_HELP.put("b21", "　");
        PROJECT_HELP.put("b22", "　暂不考核，适用于2017年及以后新建投运或实施管线改造的加油站");
        PROJECT_HELP.put("b23", "　暂不考核，适用于2017年及以后新建投运或实施管线改造的加油站");
        PROJECT_HELP.put("b24", "尽量掩蔽，不宜多设　");
        PROJECT_HELP.put("c01", "办公桌一般不超过3张；一楼设置办公室的，二楼一般不再设置　");
        PROJECT_HELP.put("c02", "　");
        PROJECT_HELP.put("c03", "　一定时期后应全部清除加油站");
        PROJECT_HELP.put("c04", "");
        PROJECT_HELP.put("c05", "从上到下一般为“办公文具”“常用文件”“个人物品”，按需设置　");
        PROJECT_HELP.put("c06", "　");
        PROJECT_HELP.put("c07", "");
        PROJECT_HELP.put("c08", "　上层“文件资料”，下层“办公用品”");
        PROJECT_HELP.put("c09", "有三层的，最下面一层可设置资料篮，整齐放置待装订资料");
        PROJECT_HELP.put("c10", "暂不考核，有特殊要求的除外　");
        PROJECT_HELP.put("c11", "其它地方摆放办公用品的暂不考核，2019年1月1日起执行考核　");
        PROJECT_HELP.put("c12", "　多余空间可放置备用账表册");
        PROJECT_HELP.put("c13", "　与标签不符暂不考核，需完善分类优化");
        PROJECT_HELP.put("c14", "其它文件柜不设置二级清单　");
        PROJECT_HELP.put("c15", "　");
        PROJECT_HELP.put("c16", "　文件夹可用A4纸长边制作");
        PROJECT_HELP.put("c17", "备用清洁用品、常用工具不得放置在文件柜内（防爆电筒除外），不首选设置在办公室内（无条件的除外）　");
        PROJECT_HELP.put("c18", "　不设置二级清单");
        PROJECT_HELP.put("c19", "　");
        PROJECT_HELP.put("c20", "二楼办公室不粘贴，便利店库房不粘贴　");
        PROJECT_HELP.put("c21", "桌面物品、主机箱　");
        PROJECT_HELP.put("c22", "　");
        PROJECT_HELP.put("c23", "方便实用就可以　");
        PROJECT_HELP.put("c24", "暂不考核　");
        PROJECT_HELP.put("c25", "　");
        PROJECT_HELP.put("c26", "　");
        PROJECT_HELP.put("c27", "　键盘、鼠标、显示器共用");
        PROJECT_HELP.put("c28", "　");
        PROJECT_HELP.put("c29", "　");
        PROJECT_HELP.put("c30", "　");
        PROJECT_HELP.put("c31", "");
        PROJECT_HELP.put("d01", "提出优化建议　");
        PROJECT_HELP.put("d02", "　台面下不能放置收银钱箱的可用抽屉，尽量不取消");
        PROJECT_HELP.put("d03", "　");
        PROJECT_HELP.put("d04", "");
        PROJECT_HELP.put("d05", "　");
        PROJECT_HELP.put("d06", "　");
        PROJECT_HELP.put("d07", "");
        PROJECT_HELP.put("d08", "　提出优化建议（保险柜、非油商品、收银钱箱不粘贴？）");
        PROJECT_HELP.put("d09", "");
        PROJECT_HELP.put("d10", "需细化描述　");
        PROJECT_HELP.put("d11", "文件夹标签可用A4纸长边制作　");
        PROJECT_HELP.put("d12", "　");
        PROJECT_HELP.put("d13", "　有必要设置的设备除外");
        PROJECT_HELP.put("d14", "　");
        PROJECT_HELP.put("d15", "　");
        PROJECT_HELP.put("d16", "　");
        PROJECT_HELP.put("d17", "　");
        PROJECT_HELP.put("d18", "　");
        PROJECT_HELP.put("d19", "　");
        PROJECT_HELP.put("d20", "　");
        PROJECT_HELP.put("e01", "广告灯箱光源须全时段开启；8点至17点59分，光线充足的站，吊顶灯须开启50%以上；18点至第二天7点59分，吊顶灯须全部开启；有报修记录的除外　");
        PROJECT_HELP.put("e02", "在顾客能够触及到地方，所放置的商品均应用于销售，为此，必须要明码标价（有价签或POP/爆炸卡均可），且价签须靠左陈列。　");
        PROJECT_HELP.put("e03", "　商品的正面应面向顾客。");
        PROJECT_HELP.put("e04", "为保证商品的丰满和量感陈列，以及易于顾客取拿的原则，加油站应主动调整货架层板与商品的间距，保持不少于二指的高度和不多于三到四指的高度。");
        PROJECT_HELP.put("e05", "");
        PROJECT_HELP.put("e06", "普通货架每90公分货架长度，缺货超过30公分，视为严重缺货。回型货架单个层板缺货超过一半，视为严重缺货。　");
        PROJECT_HELP.put("e07", "");
        PROJECT_HELP.put("e08", "室内堆头原则上总高度不超过0.8米，如有特殊陈列须向公司报备，有报备手续的除外。靠壁堆头首层须割箱陈列。");
        PROJECT_HELP.put("e09", "原则不得遮挡橱窗玻璃，地堆高度0.8米为宜，高于1米的视为过高。");
        PROJECT_HELP.put("e10", "针对岛上有堆头加油站进行考核　");
        PROJECT_HELP.put("e11", "针对有快餐区的加油站　");
        PROJECT_HELP.put("e12", "　标准店及高级店纳入考核，顾客目视可及的地方均纳入考核范围，可放置促销赠品");
        PROJECT_HELP.put("e13", "　针对有购物篮、购物车的加油站");
        PROJECT_HELP.put("e14", "　");
        PROJECT_HELP.put("e15", "　");
        PROJECT_HELP.put("e16", "　");
        PROJECT_HELP.put("e17", "磁性拨码器是用来方便库房计算进出货数量品种、盘库用的　");
        PROJECT_HELP.put("e18", "　");
        PROJECT_HELP.put("e19", "针对开展快餐业务的加油站，应在熟食类商品存储区域张贴管控表　");
        PROJECT_HELP.put("e20", "非入库赠品指非卖品赠品。　");
        PROJECT_HELP.put("e21", "　");
        PROJECT_HELP.put("e22", "　");
        PROJECT_HELP.put("e23", "　");
        PROJECT_HELP.put("e24", "　");
        PROJECT_HELP.put("e25", "　");
        PROJECT_HELP.put("e26", "　");
        PROJECT_HELP.put("e27", "无便利店的放置在办公室适当位置");
        PROJECT_HELP.put("f01", "　");
        PROJECT_HELP.put("f02", "　");
        PROJECT_HELP.put("f03", "　不要求粘贴定位标识标线");
        PROJECT_HELP.put("f04", "");
        PROJECT_HELP.put("f05", "");
        PROJECT_HELP.put("f06", "　");
        PROJECT_HELP.put("f07", "");
        PROJECT_HELP.put("f08", "");
        PROJECT_HELP.put("f09", "");
        PROJECT_HELP.put("f10", "　");
        PROJECT_HELP.put("f11", "　");
        PROJECT_HELP.put("f12", "");
        PROJECT_HELP.put("f13", "　");
        PROJECT_HELP.put("f14", "　");
        PROJECT_HELP.put("f15", "　暂不考核");
        PROJECT_HELP.put("f16", "　参照细节管理手册");
        PROJECT_HELP.put("f17", "随机抽查两名现场当班员工的员工柜　");
        PROJECT_HELP.put("f18", "　");
        PROJECT_HELP.put("f19", "　");
        PROJECT_HELP.put("f20", "　");
        PROJECT_HELP.put("f21", "　");
        PROJECT_HELP.put("f22", "　");
        PROJECT_HELP.put("f23", "　主要针对未明确考核标准的区域");
        PROJECT_HELP.put("g01", "　90度指示牌仅用于厕所不醒目的站");
        PROJECT_HELP.put("g02", "　");
        PROJECT_HELP.put("g03", "　五种提示牌");
        PROJECT_HELP.put("g04", "");
        PROJECT_HELP.put("g05", "");
        PROJECT_HELP.put("g06", "暂不考核　");
        PROJECT_HELP.put("g07", "直径约30cm为宜，分公司内统一型号");
        PROJECT_HELP.put("g08", "");
        PROJECT_HELP.put("g09", "");
        PROJECT_HELP.put("g10", "　");
        PROJECT_HELP.put("g11", "　");
        PROJECT_HELP.put("g12", "");
        PROJECT_HELP.put("g13", "　");
        PROJECT_HELP.put("g14", "　");
        PROJECT_HELP.put("g15", "　");
        PROJECT_HELP.put("g16", "　重点检查可视部分");
        PROJECT_HELP.put("g17", "　");
        PROJECT_HELP.put("g18", "　");
        PROJECT_HELP.put("g19", "　");
        PROJECT_HELP.put("g20", "　");*/

    }
}
