package com.fh.entity.qizhe;

import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;

public class ProjectAuditHelperHans {

    public static Map<String, String> PROJECT_INFO = new LinkedHashMap<>();

    public static Map<String, String> UPPER_CASE_INFO = new HashMap<>();

    public static Map<String, String> PROJECT_HELP = new HashMap<>();

    static {
        PROJECT_INFO.put("1", "苏宁店招、LOGO明显无遮挡，干净无破损，夜间（营业后2H）发光，外墙、外部橱窗干净明亮");
        PROJECT_INFO.put("2", "户外LED文字屏、彩屏正常放映，内容未过期，外立面广告位广告画面内容无过期、无破损");
        PROJECT_INFO.put("3", "门前三包区域无垃圾杂物，无小贩、大量电动车影响出入");
        PROJECT_INFO.put("4", "主通道、展厅灯光均有打开，光线充足；店内温度适当舒服；");
        PROJECT_INFO.put("5", "背景音乐音量合适，可以听到，但不影响交谈（无背景音乐不给分）");
        PROJECT_INFO.put("6", "地面、墙面清洁，垃圾桶无堆满，现场无杂物堆积、无黄纸箱、无废弃展台。");
        PROJECT_INFO.put("7", "多楼层门店每层至少开启一组自动扶梯，未开启则扣分（无电梯或关闭下行电梯不扣分）");
        PROJECT_INFO.put("8", "店内有楼层导引、功能区（卫生间、服务台等）导引");
        PROJECT_INFO.put("9", "设备完好，正常使用，地面、台面、镜面、马桶等整洁干净，空气清新无异味（无卫生间正常给分）");
        PROJECT_INFO.put("10", "无私接乱接电源、违规使用大功率电器现象（如电瓶车充电、电水壶烧水等）");
        PROJECT_INFO.put("11", "防火门处于常闭不落锁状态，防火卷帘门下无任何物品");
        PROJECT_INFO.put("12", "样机无破损、污渍等瑕疵缺陷，商品摆放整齐，无乱扔现象");
        PROJECT_INFO.put("13", "可容性样机（冰箱、洗衣机、电饭煲、微波炉）内未摆放杂物（展示用品不违规）");
        PROJECT_INFO.put("14", "单个品牌出现缺样且无布展情况");
        PROJECT_INFO.put("15", "拔出真机的防盗器发出警报，出警报后10秒有人处理");
        PROJECT_INFO.put("16", "无手写/涂改价签的现象、无使用其他物料代替价签的现象");
        PROJECT_INFO.put("17", "店内布展物料中无厂家二维码、联系方式、网址等信息");
        PROJECT_INFO.put("18", "无促销活动指导书、商品库存表、顾客购买台帐外露现象");
        PROJECT_INFO.put("19", "全体人员佩戴工牌、全套工装，穿着整洁干净");
        PROJECT_INFO.put("20", "营业期间站姿自然，无坐岗、趴柜、靠柜以及3人以上聚岗现象");
        PROJECT_INFO.put("21", "无横屏看手机现象，竖屏看手机走近3米内放下手机 ");
        PROJECT_INFO.put("22", "在顾客要寻求帮助、有眼神交汇时或遇到询问时，对顾客说您好欢迎光临，或微笑示意");
        PROJECT_INFO.put("23", "顾客进入展厅展柜后1分钟内有人接待，遇忙时客气的请顾客稍等片刻");
        PROJECT_INFO.put("24", "有顾客服务时收银人员双手交递物品");
        PROJECT_INFO.put("25", "店内提供免费WIFI且至少达到2格信号，2分钟内完成一个20M的APP下载");
        PROJECT_INFO.put("26", "POS机背景、吊板、立式立牌、台卡中均有30/365的服务承诺展示");
        PROJECT_INFO.put("27", "收银台、POS台、服务台、打卡机处有公示苏宁投诉渠道");
        PROJECT_INFO.put("28", "收银台/服务台有扫码反馈布展，无人的收银台摆放“暂停收银”台卡");
        PROJECT_INFO.put("29", "是否发现飞单、私收现金、窜码开票、虚假销售等违规销售，是否发现私设pos机/个人收款二维码/私刻印章/私买收据等情况");
        PROJECT_INFO.put("30", "随机询价3个大家电商品，是否存在报价低于挂牌价10%的现象；随机询价2个3C/小家电商品，是否存在报价低于挂牌价5%的现象");
        PROJECT_INFO.put("31", "表明家中有旧家电需处理，销售人员是否表示有不通过苏宁收旧的渠道");
        PROJECT_INFO.put("32", "苏宁快修点位是否配备电脑、打印机、监控摄像头、三脚架；\n" +
                "苏宁快修维修工具是否配备防静电垫、台灯、螺丝刀、镊子、钳子、吸盘、夹具、拨片、稳压电源、万用表、恒温烙铁、热风枪、酒精瓶（含酒精）、海绵、毛刷、无尘布；\n" +
                "苏宁快修形象是否有标准工装、防静电手环、标准背景墙、标准快修桌、区域卫生、桌面整洁、价格公示、暂停服务牌、下单邀评活动单页、名片架；");
        PROJECT_INFO.put("S4", "顾客结账时：主动询问顾客是否有别的需求，主动询问“您好，还需要点什么吗？”或者主动面销相关活动或商品【声音宏亮，口齿清晰，话语完整】对顾客的购买，进行关联性活动或商品的面销都可得分");


        for (String key : PROJECT_INFO.keySet()) {
            UPPER_CASE_INFO.put(key, key.toUpperCase());
        }


    /*    PROJECT_HELP.put("a01", "　");
        PROJECT_HELP.put("a02", "　");
        PROJECT_HELP.put("a03", "　一定时期后应全部清除加油站");
        PROJECT_HELP.put("a04", "　暂不考核");
        PROJECT_HELP.put("a05", "可用A4纸黑白打印装订成册　");
        PROJECT_HELP.put("a06", "先期考核办公室、加油现场（含站房四周）、配发电间、厨房餐厅、员工宿舍、活动室，2018年7月起全面考核　");
        PROJECT_HELP.put("a07", "先期考核办公室、加油现场（含站房四周）、配发电间、厨房餐厅、员工宿舍、活动室，2018年7月起全面考核　");
        PROJECT_HELP.put("a08", "　");
        PROJECT_HELP.put("a09", "　暂不考核，规范后考核");
        PROJECT_HELP.put("a10", "其它项有考核的除外　");
        PROJECT_HELP.put("a11", "重点关注顾客可视的加油现场、加油设备、主立牌灯箱、罩棚、立柱、墙面、绿化等，其它项有考核的除外　");
        PROJECT_HELP.put("a12", "　暂不考核，2018年7月起全面考核");
        PROJECT_HELP.put("a13", "　暂不考核，2018年7月起全面考核");
        PROJECT_HELP.put("a14", "　");
        PROJECT_HELP.put("a15", "　");
        PROJECT_HELP.put("a16", "　办公室可放置在个人物品柜里，加油现场可根据需要设置物品整理箱");
        PROJECT_HELP.put("a17", "　");
        PROJECT_HELP.put("a18", "　备用帐表册可叠放，不用放于档案盒");
        PROJECT_HELP.put("a19", "　");
        PROJECT_HELP.put("a20", "一组电源开关一个　");
        PROJECT_HELP.put("a21", "　");
        PROJECT_HELP.put("a22", "　便利店内可安装在柜门内侧");
        PROJECT_HELP.put("a23", "　");
        PROJECT_HELP.put("a24", "　");
        PROJECT_HELP.put("a25", "卫生间洗手盆的水龙头已粘贴“请节约用水”提示的除外　");
        PROJECT_HELP.put("a26", "左右开启的窗帘不设开启线，但开启状态应统一　");
        PROJECT_HELP.put("a27", "　");
        PROJECT_HELP.put("a28", "粘贴在高处，粘贴方式需优化　");
        PROJECT_HELP.put("a29", "　其它项有考核的除外");
        PROJECT_HELP.put("a30", "　");
        PROJECT_HELP.put("a31", "初期室内未作隐蔽处理，但只有一个线槽的考核　");
        PROJECT_HELP.put("a32", "暂不考核，适用于2017年及以后新建投运或实施站房技改的加油站　");
        PROJECT_HELP.put("b01", "参照细节管理手册，侧重加油岛和标准物件，垃圾桶不需要每岛一个　");
        PROJECT_HELP.put("b02", "暂不考核，2018年5月20日起全面考核　");
        PROJECT_HELP.put("b03", "　暂不考核，2018年5月20日起全面考核");
        PROJECT_HELP.put("b04", "　暂不考核，2018年5月20日起全面考核");
        PROJECT_HELP.put("b05", "直径约30cm为宜，分公司内统一型号，不具备条件的可不配置　");
        PROJECT_HELP.put("b06", "先期考核办公室、加油现场（含站房四周）、配发电间、厨房餐厅、员工宿舍、活动室，2018年7月起全面考核　");
        PROJECT_HELP.put("b07", "绿植除外　");
        PROJECT_HELP.put("b08", "　");
        PROJECT_HELP.put("b09", "　便利店前、加油现场");
        PROJECT_HELP.put("b10", "暂不考核　");
        PROJECT_HELP.put("b11", "加油枪直接向摩托车加油的除外　");
        PROJECT_HELP.put("b12", "　加油枪直接向摩托车加油的除外");
        PROJECT_HELP.put("b13", "　");
        PROJECT_HELP.put("b14", "　");
        PROJECT_HELP.put("b15", "　");
        PROJECT_HELP.put("b16", "　暂不考核");
        PROJECT_HELP.put("B17", "结合实际情况评判是否扣分　");
        PROJECT_HELP.put("b18", "　厕所设置在便利店内的，厕所内可适量设置拖把");
        PROJECT_HELP.put("b19", "　");
        PROJECT_HELP.put("b20", "　");
        PROJECT_HELP.put("b21", "　");
        PROJECT_HELP.put("b22", "　暂不考核，适用于2017年及以后新建投运或实施管线改造的加油站");
        PROJECT_HELP.put("b23", "　暂不考核，适用于2017年及以后新建投运或实施管线改造的加油站");
        PROJECT_HELP.put("b24", "尽量掩蔽，不宜多设　");
        PROJECT_HELP.put("c01", "办公桌一般不超过3张；一楼设置办公室的，二楼一般不再设置　");
        PROJECT_HELP.put("c02", "　");
        PROJECT_HELP.put("c03", "　一定时期后应全部清除加油站");
        PROJECT_HELP.put("c04", "");
        PROJECT_HELP.put("c05", "从上到下一般为“办公文具”“常用文件”“个人物品”，按需设置　");
        PROJECT_HELP.put("c06", "　");
        PROJECT_HELP.put("c07", "");
        PROJECT_HELP.put("c08", "　上层“文件资料”，下层“办公用品”");
        PROJECT_HELP.put("c09", "有三层的，最下面一层可设置资料篮，整齐放置待装订资料");
        PROJECT_HELP.put("c10", "暂不考核，有特殊要求的除外　");
        PROJECT_HELP.put("c11", "其它地方摆放办公用品的暂不考核，2019年1月1日起执行考核　");
        PROJECT_HELP.put("c12", "　多余空间可放置备用账表册");
        PROJECT_HELP.put("c13", "　与标签不符暂不考核，需完善分类优化");
        PROJECT_HELP.put("c14", "其它文件柜不设置二级清单　");
        PROJECT_HELP.put("c15", "　");
        PROJECT_HELP.put("c16", "　文件夹可用A4纸长边制作");
        PROJECT_HELP.put("c17", "备用清洁用品、常用工具不得放置在文件柜内（防爆电筒除外），不首选设置在办公室内（无条件的除外）　");
        PROJECT_HELP.put("c18", "　不设置二级清单");
        PROJECT_HELP.put("c19", "　");
        PROJECT_HELP.put("c20", "二楼办公室不粘贴，便利店库房不粘贴　");
        PROJECT_HELP.put("c21", "桌面物品、主机箱　");
        PROJECT_HELP.put("c22", "　");
        PROJECT_HELP.put("c23", "方便实用就可以　");
        PROJECT_HELP.put("c24", "暂不考核　");
        PROJECT_HELP.put("c25", "　");
        PROJECT_HELP.put("c26", "　");
        PROJECT_HELP.put("c27", "　键盘、鼠标、显示器共用");
        PROJECT_HELP.put("c28", "　");
        PROJECT_HELP.put("c29", "　");
        PROJECT_HELP.put("c30", "　");
        PROJECT_HELP.put("c31", "");
        PROJECT_HELP.put("d01", "提出优化建议　");
        PROJECT_HELP.put("d02", "　台面下不能放置收银钱箱的可用抽屉，尽量不取消");
        PROJECT_HELP.put("d03", "　");
        PROJECT_HELP.put("d04", "");
        PROJECT_HELP.put("d05", "　");
        PROJECT_HELP.put("d06", "　");
        PROJECT_HELP.put("d07", "");
        PROJECT_HELP.put("d08", "　提出优化建议（保险柜、非油商品、收银钱箱不粘贴？）");
        PROJECT_HELP.put("d09", "");
        PROJECT_HELP.put("d10", "需细化描述　");
        PROJECT_HELP.put("d11", "文件夹标签可用A4纸长边制作　");
        PROJECT_HELP.put("d12", "　");
        PROJECT_HELP.put("d13", "　有必要设置的设备除外");
        PROJECT_HELP.put("d14", "　");
        PROJECT_HELP.put("d15", "　");
        PROJECT_HELP.put("d16", "　");
        PROJECT_HELP.put("d17", "　");
        PROJECT_HELP.put("d18", "　");
        PROJECT_HELP.put("d19", "　");
        PROJECT_HELP.put("d20", "　");
        PROJECT_HELP.put("e01", "广告灯箱光源须全时段开启；8点至17点59分，光线充足的站，吊顶灯须开启50%以上；18点至第二天7点59分，吊顶灯须全部开启；有报修记录的除外　");
        PROJECT_HELP.put("e02", "在顾客能够触及到地方，所放置的商品均应用于销售，为此，必须要明码标价（有价签或POP/爆炸卡均可），且价签须靠左陈列。　");
        PROJECT_HELP.put("e03", "　商品的正面应面向顾客。");
        PROJECT_HELP.put("e04", "为保证商品的丰满和量感陈列，以及易于顾客取拿的原则，加油站应主动调整货架层板与商品的间距，保持不少于二指的高度和不多于三到四指的高度。");
        PROJECT_HELP.put("e05", "");
        PROJECT_HELP.put("e06", "普通货架每90公分货架长度，缺货超过30公分，视为严重缺货。回型货架单个层板缺货超过一半，视为严重缺货。　");
        PROJECT_HELP.put("e07", "");
        PROJECT_HELP.put("e08", "室内堆头原则上总高度不超过0.8米，如有特殊陈列须向公司报备，有报备手续的除外。靠壁堆头首层须割箱陈列。");
        PROJECT_HELP.put("e09", "原则不得遮挡橱窗玻璃，地堆高度0.8米为宜，高于1米的视为过高。");
        PROJECT_HELP.put("e10", "针对岛上有堆头加油站进行考核　");
        PROJECT_HELP.put("e11", "针对有快餐区的加油站　");
        PROJECT_HELP.put("e12", "　标准店及高级店纳入考核，顾客目视可及的地方均纳入考核范围，可放置促销赠品");
        PROJECT_HELP.put("e13", "　针对有购物篮、购物车的加油站");
        PROJECT_HELP.put("e14", "　");
        PROJECT_HELP.put("e15", "　");
        PROJECT_HELP.put("e16", "　");
        PROJECT_HELP.put("e17", "磁性拨码器是用来方便库房计算进出货数量品种、盘库用的　");
        PROJECT_HELP.put("e18", "　");
        PROJECT_HELP.put("e19", "针对开展快餐业务的加油站，应在熟食类商品存储区域张贴管控表　");
        PROJECT_HELP.put("e20", "非入库赠品指非卖品赠品。　");
        PROJECT_HELP.put("e21", "　");
        PROJECT_HELP.put("e22", "　");
        PROJECT_HELP.put("e23", "　");
        PROJECT_HELP.put("e24", "　");
        PROJECT_HELP.put("e25", "　");
        PROJECT_HELP.put("e26", "　");
        PROJECT_HELP.put("e27", "无便利店的放置在办公室适当位置");
        PROJECT_HELP.put("f01", "　");
        PROJECT_HELP.put("f02", "　");
        PROJECT_HELP.put("f03", "　不要求粘贴定位标识标线");
        PROJECT_HELP.put("f04", "");
        PROJECT_HELP.put("f05", "");
        PROJECT_HELP.put("f06", "　");
        PROJECT_HELP.put("f07", "");
        PROJECT_HELP.put("f08", "");
        PROJECT_HELP.put("f09", "");
        PROJECT_HELP.put("f10", "　");
        PROJECT_HELP.put("f11", "　");
        PROJECT_HELP.put("f12", "");
        PROJECT_HELP.put("f13", "　");
        PROJECT_HELP.put("f14", "　");
        PROJECT_HELP.put("f15", "　暂不考核");
        PROJECT_HELP.put("f16", "　参照细节管理手册");
        PROJECT_HELP.put("f17", "随机抽查两名现场当班员工的员工柜　");
        PROJECT_HELP.put("f18", "　");
        PROJECT_HELP.put("f19", "　");
        PROJECT_HELP.put("f20", "　");
        PROJECT_HELP.put("f21", "　");
        PROJECT_HELP.put("f22", "　");
        PROJECT_HELP.put("f23", "　主要针对未明确考核标准的区域");
        PROJECT_HELP.put("g01", "　90度指示牌仅用于厕所不醒目的站");
        PROJECT_HELP.put("g02", "　");
        PROJECT_HELP.put("g03", "　五种提示牌");
        PROJECT_HELP.put("g04", "");
        PROJECT_HELP.put("g05", "");
        PROJECT_HELP.put("g06", "暂不考核　");
        PROJECT_HELP.put("g07", "直径约30cm为宜，分公司内统一型号");
        PROJECT_HELP.put("g08", "");
        PROJECT_HELP.put("g09", "");
        PROJECT_HELP.put("g10", "　");
        PROJECT_HELP.put("g11", "　");
        PROJECT_HELP.put("g12", "");
        PROJECT_HELP.put("g13", "　");
        PROJECT_HELP.put("g14", "　");
        PROJECT_HELP.put("g15", "　");
        PROJECT_HELP.put("g16", "　重点检查可视部分");
        PROJECT_HELP.put("g17", "　");
        PROJECT_HELP.put("g18", "　");
        PROJECT_HELP.put("g19", "　");
        PROJECT_HELP.put("g20", "　");*/

    }
}
